version: '3'

services:
    bnbnode:
        build: "./bnbchain"
        ports:
            # rpc port
            - "26658:26657"
        volumes:
            - "./bnbchain/start-new-chain.sh:/opt/bnbchaind/start-new-chain.sh"
        command: ["bash", "/opt/bnbchaind/start-new-chain.sh"]
    # bnbchainrest:
    #     build: "./bnbchain"
    #     ports:
    #         - "1317:1317"
    #     command: ["bnbcli", "api-server", "--node=tcp://bnbchain:26657", "--laddr=tcp://0.0.0.0:1317", "--trust-node"]
    deputy:
        build:
            context: ".." # relative to docker-compose.yaml
            dockerfile: "integration_test/deputy/Dockerfile" # relative to context directory
        volumes:
            - "./deputy/config.json:/deputy/config/config.json"
    kavanode:
        image: "kava/kava-deputy-test:v0.8.1" # TODO change name?
        ports:
            # default kava rpc port
            - "26657:26657"
        volumes:
            - "./kava/:/root/kava/config"
        command: ["bash", "/root/kava/config/start-new-chain.sh"]
