version: '3'

services:
    bnbnode:
        build: "./bnbchain"
        ports:
            # open rpc port
            - "26658:26657"
        volumes:
            - "./bnbchain/start-new-chain.sh:/opt/bnbchaind/start-new-chain.sh"
        command: ["bash", "/opt/bnbchaind/start-new-chain.sh"]
    deputy:
        build:
            context: ".." # relative to docker-compose.yaml
            dockerfile: "integration_test/deputy/Dockerfile" # relative to context directory
        volumes:
            - "./deputy/config.json:/deputy/config/config.json"
    kavanode:
        image: "kava/kava-deputy-test:v0.8.1" # TODO change name?
        ports:
            # open default kava rpc port
            - "26657:26657"
        volumes:
            - "./kava/:/root/kava/config"
        command: ["bash", "/root/kava/config/start-new-chain.sh"]
